import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2C5F8B',
    padding: 20,
  },
  logo: { width: 150, height: 150, marginBottom: 20 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#FFFFFF', marginBottom: 10, textAlign: 'center' },
  subtitle: { fontSize: 16, color: '#E8F4F8', textAlign: 'center', marginHorizontal: 20, marginBottom: 30, lineHeight: 22 },
  greenButton: { backgroundColor: '#3A7D44', paddingVertical: 12, paddingHorizontal: 30, borderRadius: 25, minWidth: 150, alignItems: 'center', borderWidth: 2, borderColor: '#FFFFFF' },
  buttonText: { fontSize: 18, color: '#FFFFFF', fontWeight: 'bold' },
  homeContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  header: { backgroundColor: '#2C5F8B', width: '100%', paddingVertical: 20, alignItems: 'center', elevation: 5 },
  headerLogo: { width: 60, height: 60, marginBottom: 10 },
  headerText: { fontSize: 20, fontWeight: 'bold', color: '#FFFFFF', textTransform: 'uppercase', textAlign: 'center', paddingHorizontal: 10, letterSpacing: 1 },
  headerDivider: { height: 3, width: '30%', backgroundColor: '#3A7D44', marginTop: 10 },
  scrollContainer: { padding: 15 },
  buttonsContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around' },
  card: { width: '45%', aspectRatio: 1, alignItems: 'center', justifyContent: 'center', padding: 15, borderRadius: 12, marginBottom: 15, borderWidth: 7, borderColor: '#3A7D44', shadowOpacity: 0.15, elevation: 4 },
  imageContainer: { width: 80, height: 80, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  cardImage: { width: '100%', height: '100%' },
  cardText: { fontSize: 16, color: '#FFFFFF', fontWeight: '600', textAlign: 'center' },
  infoContainer: { flex: 1, padding: 20, backgroundColor: '#FFFFFF' },
  infoTitle: { fontSize: 24, fontWeight: 'bold', color: '#2C5F8B', marginBottom: 20, textAlign: 'center' },
  sectionSubtitle: { fontSize: 18, color: '#555', textAlign: 'center', marginBottom: 20 },
  sectionHeader: { fontSize: 18, fontWeight: 'bold', color: '#2C5F8B', marginTop: 15, marginBottom: 10 },
  stepCard: { backgroundColor: '#F8F9FA', borderRadius: 10, padding: 15, marginBottom: 15, borderLeftWidth: 4, borderLeftColor: '#3A7D44' },
  stepNumber: { backgroundColor: '#2C5F8B', width: 30, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  stepNumberText: { color: '#FFF', fontWeight: 'bold' },
  stepContent: { flex: 1 },
  stepTitle: { fontSize: 16, fontWeight: 'bold', color: '#2C5F8B', marginBottom: 5 },
  stepDates: { fontSize: 14, color: '#E67E22', fontWeight: '600', marginBottom: 5 },
  stepDescription: { fontSize: 14, color: '#555' },
  infoItem: { marginBottom: 8 },
  infoItemText: { fontSize: 16, color: '#333' },
  careersContainer: { marginVertical: 15 },
  careerItem: { backgroundColor: '#F8F9FA', padding: 15, borderRadius: 8, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: '#3A7D44' },
  careerName: { fontSize: 16, fontWeight: '600', color: '#2C5F8B' },
  careerTurn: { fontSize: 14, color: '#555', marginTop: 5 },
  noteText: { fontSize: 14, color: '#777', textAlign: 'center', marginTop: 10, fontStyle: 'italic' },
  warningCard: { backgroundColor: '#FFF3CD', padding: 15, borderRadius: 8, marginTop: 20, borderLeftWidth: 4, borderLeftColor: '#FFC107' },
  warningText: { color: '#856404' },
  actionButton: { backgroundColor: '#3A7D44', padding: 15, borderRadius: 8, marginTop: 20, alignItems: 'center' },
  actionButtonText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
  contactButtons: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 20 },
  contactButton: { padding: 15, borderRadius: 8, width: '45%', alignItems: 'center' },
  contactButtonText: { color: '#FFF', fontWeight: 'bold' },
});

export default styles;
